version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
configuration: Release
platform: x86
before_build:
- cmd: git submodule update --init --recursive
build:
  project: SA2ModLoader.sln
  verbosity: minimal
after_build:
- cmd: >-
    mkdir C:\sa2mm

    mkdir C:\sa2mm\extlib

    mkdir C:\sa2mm\extlib\BASS

    copy C:\projects\sa2-mod-loader\bin\SA2ModLoader.dll C:\sa2mm\SA2ModLoader.dll

    copy C:\projects\sa2-mod-loader\data\*.* C:\sa2mm\

    copy C:\projects\sa2-mod-loader\extlib\bass\*.dll C:\sa2mm\extlib\BASS\    

    echo | set /p dummyName="%APPVEYOR_BUILD_VERSION%" > "C:\sa2mm\sa2mlver.txt"

    7z a C:\projects\sa2-mod-loader\bin\SA2ModLoader.7z C:\sa2mm\*
artifacts:
- path: bin\SA2ModLoader.7z

- path: bin\SA2ModLoader.pdb

before_deploy:
- ps: |-
      if (!$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED) {
        $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED = "$env:APPVEYOR_REPO_COMMIT_MESSAGE"
      }

deploy:
- provider: GitHub
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
  auth_token:
    secure: WwdJ8DbEJO7DM1m+oJVoa4ZXIMQKQ2d18oUQF9RDDNZNbNzXrd+pq5NpemZIhTAWMnWFPo7TxXDNj0Ra6j9hCIG5/1by5SSerA/EwT7ZayChH3V7HZ68i/7SKgwgxLPI
  artifact: bin/SA2ModLoader.7z,bin/SA2ModLoader.pdb
  on:
    branch: master
